terraform fmt applied

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,8 +87,8 @@ jobs:
       - name: Terraform init
         run: terraform init
         env:
-          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       - name: Terraform Validate
         run: terraform validate
@@ -99,8 +99,8 @@ jobs:
       - name: Terraform plan
         run: terraform plan
         env:
-          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       # Apply with bDeployBlue=false to deploy the Green environment
       - name: Terraform apply (Green Deploy)
@@ -108,8 +108,8 @@ jobs:
           IMAGE_TAG=$(git rev-parse --short HEAD)
           terraform apply -var="image_tag=$IMAGE_TAG" -var="bDeployBlue=false" -auto-approve
         env:
-          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
   test_green:
     name: 'Test Green Environment'
@@ -123,19 +123,17 @@ jobs:
           echo "::set-output name=health_check_id::$GREEN_HEALTH_CHECK_ID"
           
       - name: Check Health of Green Bucket
-      run: |
-        HEALTH_STATUS=$(aws route53 get-health-check-status --health-check-id ${{ steps.fetch_health_check_id.outputs.health_check_id }} --query 'HealthCheckObservations[].StatusReport.Status' --output text)
-        echo "Health check statuses: $HEALTH_STATUS"
-        
-        # Check if all statuses contain "HTTP Status Code 200, OK"
-        if echo "$HEALTH_STATUS" | grep -qv "HTTP Status Code 200, OK"; then
-          echo "Health check failed in at least one region."
-          exit 1
-        else
-          echo "Green bucket is healthy across all regions."
-        fi
-        
-        
+        run: |
+          HEALTH_STATUS=$(aws route53 get-health-check-status --health-check-id ${{ steps.fetch_health_check_id.outputs.health_check_id }} --query 'HealthCheckObservations[].StatusReport.Status' --output text)
+          echo "Health check statuses: $HEALTH_STATUS"
+          
+          # Check if all statuses contain "HTTP Status Code 200, OK"
+          if echo "$HEALTH_STATUS" | grep -qv "HTTP Status Code 200, OK"; then
+            echo "Health check failed in at least one region."
+            exit 1
+          else
+            echo "Green bucket is healthy across all regions."
+          fi
 
   promote_green:
     name: 'Promote Green to Blue (Final Deploy)'
@@ -154,5 +152,5 @@ jobs:
           IMAGE_TAG=$(git rev-parse --short HEAD)
           terraform apply -var="image_tag=$IMAGE_TAG" -var="bDeployBlue=true" -auto-approve
         env:
-          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
